cmake_minimum_required(VERSION 3.20)
project(AegisAV LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_library(aegis_core
    src/util.cpp src/hash.cpp src/signatures.cpp src/http.cpp src/quarantine.cpp
    src/scanner.cpp src/watcher.cpp src/process_monitor.cpp src/service.cpp)
target_include_directories(aegis_core PUBLIC include)
target_compile_definitions(aegis_core PRIVATE UNICODE _UNICODE WIN32_LEAN_AND_MEAN NOMINMAX)
target_link_libraries(aegis_core PUBLIC bcrypt winhttp wintrust crypt32 shell32 advapi32)
add_executable(AegisAV src/main.cpp)
target_link_libraries(AegisAV PRIVATE aegis_core)
target_compile_definitions(AegisAV PRIVATE UNICODE _UNICODE)
add_executable(AegisAV_UI WIN32 src/gui.cpp)
target_link_libraries(AegisAV_UI PRIVATE aegis_core comdlg32 shell32)
target_compile_definitions(AegisAV_UI PRIVATE UNICODE _UNICODE)
if(MSVC)
  target_compile_options(aegis_core PRIVATE /W4 /permissive- /EHsc)
  target_compile_options(AegisAV PRIVATE /W4 /EHsc)
  target_compile_options(AegisAV_UI PRIVATE /W4 /EHsc)
endif()
