#include "aegis/core.h"
#include <windows.h>
#include <commdlg.h>
#include <shellapi.h>
#include <string>

using namespace aegis;
static HWND g_list=nullptr,g_status=nullptr;static Config g_cfg;static SignatureDb g_db;static Scanner* g_scanner=nullptr;
static void add(const std::wstring&s){SendMessageW(g_list,LB_ADDSTRING,0,(LPARAM)s.c_str());}
static std::wstring result_line(const ScanResult&r){return L"["+to_wide(verdict_string(r.verdict))+L"] "+r.path.wstring()+L"  score="+std::to_wstring(r.score);}
static void scan_file(HWND h){wchar_t file[32768]{};OPENFILENAMEW o{};o.lStructSize=sizeof(o);o.hwndOwner=h;o.lpstrFile=file;o.nMaxFile=32768;o.lpstrFilter=L"All files\0*.*\0";o.Flags=OFN_FILEMUSTEXIST|OFN_PATHMUSTEXIST;if(GetOpenFileNameW(&o)){SetWindowTextW(g_status,L"Scanning...");auto r=g_scanner->scan_file(file);add(result_line(r));for(auto&f:r.findings)add(L"   +"+std::to_wstring(f.score)+L" "+to_wide(f.name+": "+f.detail));SetWindowTextW(g_status,r.verdict==Verdict::Malicious?L"MALWARE DETECTED":r.verdict==Verdict::Suspicious?L"Suspicious file":L"No threat detected");}}
static LRESULT CALLBACK proc(HWND h,UINT m,WPARAM w,LPARAM l){switch(m){case WM_CREATE:{CreateWindowW(L"STATIC",L"AegisAV",WS_CHILD|WS_VISIBLE,18,12,250,28,h,nullptr,nullptr,nullptr);CreateWindowW(L"BUTTON",L"Scan file",WS_CHILD|WS_VISIBLE,18,52,120,34,h,(HMENU)1,nullptr,nullptr);CreateWindowW(L"BUTTON",L"Update signatures",WS_CHILD|WS_VISIBLE,148,52,150,34,h,(HMENU)2,nullptr,nullptr);CreateWindowW(L"BUTTON",L"Open quarantine",WS_CHILD|WS_VISIBLE,308,52,140,34,h,(HMENU)3,nullptr,nullptr);g_status=CreateWindowW(L"STATIC",L"Ready",WS_CHILD|WS_VISIBLE,18,98,650,24,h,nullptr,nullptr,nullptr);g_list=CreateWindowW(L"LISTBOX",nullptr,WS_CHILD|WS_VISIBLE|WS_BORDER|WS_VSCROLL|LBS_NOINTEGRALHEIGHT,18,128,750,360,h,nullptr,nullptr,nullptr);return 0;}case WM_COMMAND:if(LOWORD(w)==1)scan_file(h);else if(LOWORD(w)==2){std::string e;SetWindowTextW(g_status,L"Updating...");if(g_scanner->update_signatures(e)){SetWindowTextW(g_status,L"Signatures updated");add(L"Signature database: "+std::to_wstring(g_db.size())+L" hashes");}else SetWindowTextW(g_status,to_wide("Update failed: "+e).c_str());}else if(LOWORD(w)==3)ShellExecuteW(h,L"open",g_cfg.quarantinePath.c_str(),nullptr,nullptr,SW_SHOWNORMAL);return 0;case WM_DESTROY:PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,w,l);}
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE,LPWSTR,int show){g_cfg=Config::load();std::string e;g_db.load(g_cfg.signaturesPath,e);Scanner sc(g_cfg,&g_db);g_scanner=&sc;WNDCLASSW wc{};wc.lpfnWndProc=proc;wc.hInstance=hi;wc.lpszClassName=L"AegisAVWindow";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassW(&wc);HWND h=CreateWindowW(wc.lpszClassName,L"AegisAV Security",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,810,550,nullptr,nullptr,hi,nullptr);ShowWindow(h,show);UpdateWindow(h);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessageW(&msg);}return 0;}
